site_name: Vultr Markdown Toolkit
site_description: Authoring Tools for Vultr Docs
repo_url: https://github.com/vultr/vultr-mdtk
repo_name: vultr/vultr-mdtk
edit_uri: ""
site_author: Vultr.com
copyright: '&copy; <a href="https://www.vultr.com">Vultr.com</a>'
nav:
    - 'About the Markdown Toolkit': 'index.md'
    - 'Vale Tests': 'tests.md'
    - 'License': license.md
    - 'About Vultr': 'https://www.vultr.com'
    - 'Deploy a Cloud Server': 'https://my.vultr.com'
docs_dir: docs
remote_branch: gh-pages
use_directory_urls: true
dev_addr: 127.0.0.1:8000
theme:
  name: material
  favicon: assets/images/signet__on-dark-blue-bg.png
  logo: assets/images/signet__on-dark.png
  icon:
    repo: fontawesome/brands/github  
  palette:
    scheme: preference
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc:
      permalink: true
      toc_depth: 3    
    - toc.integrate
    - search.suggest
    - search.highlight
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vultr
    - icon: fontawesome/brands/github
      link: https://github.com/vultr
extra_css:
  - stylesheets/extra.css
